// app/sw.js/route.ts
// Sirve el Service Worker con los headers correctos para que el navegador
// lo acepte sin importar la CSP que aplique Cloudflare sobre los assets estáticos.
//
// Este SW combina:
//   • Firebase Messaging compat (FCM Web Push — notificaciones de comunidad)
//   • Workbox (caching de assets)
//   • Notificaciones de clase (setTimeout locales)

import { NextResponse } from "next/server";

// Construimos el SW como array de strings para evitar problemas con
// backticks o template literals anidados en el template literal de TS.
const SW_LINES = [
  "importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');",
  "importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');",
  "",
  `firebase.initializeApp({`,
  `  apiKey: '${process.env.NEXT_PUBLIC_FIREBASE_API_KEY}',`,
  `  authDomain: '${process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',`,
  `  projectId: '${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}',`,
  `  storageBucket: '${process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',`,
  `  messagingSenderId: '${process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',`,
  `  appId: '${process.env.NEXT_PUBLIC_FIREBASE_APP_ID}',`,
  `});`,
  "",
  "var messaging = firebase.messaging();",
  "",
  "// FCM background handler",
  "messaging.onBackgroundMessage(function(payload) {",
  "  var notif = payload.notification || {};",
  "  var data  = payload.data || {};",
  "  return self.registration.showNotification(notif.title || 'SinPresupuesto', {",
  "    body:    notif.body || '',",
  "    icon:    notif.icon || '/favicon.png',",
  "    badge:   '/favicon.png',",
  "    tag:     data.tag  || 'sp-community',",
  "    vibrate: [200, 100, 200],",
  "    requireInteraction: false,",
  "    data:    { url: data.url || '/comunidad' },",
  "  });",
  "});",
  "",
  "importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');",
  "",
  "var registerRoute          = workbox.routing.registerRoute;",
  "var CacheFirst             = workbox.strategies.CacheFirst;",
  "var NetworkFirst           = workbox.strategies.NetworkFirst;",
  "var NetworkOnly            = workbox.strategies.NetworkOnly;",
  "var ExpirationPlugin       = workbox.expiration.ExpirationPlugin;",
  "var CacheableResponsePlugin = workbox.cacheableResponse.CacheableResponsePlugin;",
  "",
  "self.addEventListener('install',  function() { self.skipWaiting(); });",
  "self.addEventListener('activate', function(e) { e.waitUntil(self.clients.claim()); });",
  "",
  "registerRoute(",
  "  function(ctx) {",
  "    var url = ctx.url;",
  "    return url.hostname.includes('firebase') ||",
  "           url.hostname.includes('firebaseapp') ||",
  "           url.hostname.includes('googleapis.com') ||",
  "           url.pathname.startsWith('/api/') ||",
  "           url.pathname.startsWith('/keystatic');",
  "  },",
  "  new NetworkOnly()",
  ");",
  "",
  "registerRoute(",
  "  function(ctx) { return ctx.url.pathname.startsWith('/_next/static/'); },",
  "  new CacheFirst({",
  "    cacheName: 'sp-static-assets',",
  "    plugins: [",
  "      new CacheableResponsePlugin({ statuses: [0, 200] }),",
  "      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 31536000 }),",
  "    ],",
  "  })",
  ");",
  "",
  "registerRoute(",
  "  function(ctx) { return ctx.request.destination === 'image'; },",
  "  new CacheFirst({",
  "    cacheName: 'sp-images',",
  "    plugins: [",
  "      new CacheableResponsePlugin({ statuses: [0, 200] }),",
  "      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 2592000 }),",
  "    ],",
  "  })",
  ");",
  "",
  "registerRoute(",
  "  function(ctx) {",
  "    return ctx.url.hostname === 'fonts.googleapis.com' ||",
  "           ctx.url.hostname === 'fonts.gstatic.com';",
  "  },",
  "  new CacheFirst({",
  "    cacheName: 'sp-fonts',",
  "    plugins: [",
  "      new CacheableResponsePlugin({ statuses: [0, 200] }),",
  "      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 31536000 }),",
  "    ],",
  "  })",
  ");",
  "",
  "registerRoute(",
  "  function(ctx) { return ctx.request.destination === 'document'; },",
  "  new NetworkFirst({",
  "    cacheName: 'sp-pages',",
  "    networkTimeoutSeconds: 3,",
  "    plugins: [",
  "      new CacheableResponsePlugin({ statuses: [200] }),",
  "      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 86400 }),",
  "    ],",
  "  })",
  ");",
  "",
  "var classTimers = new Map();",
  "",
  "function cancelAllClassTimers() {",
  "  classTimers.forEach(function(id) { clearTimeout(id); });",
  "  classTimers.clear();",
  "}",
  "",
  "function scheduleNotification(n) {",
  "  if (classTimers.has(n.tag)) clearTimeout(classTimers.get(n.tag));",
  "  var id = setTimeout(function() {",
  "    classTimers.delete(n.tag);",
  "    self.registration.showNotification(n.title, {",
  "      body: n.body, tag: n.tag,",
  "      icon: '/favicon.png', badge: '/favicon.png',",
  "      vibrate: [200, 100, 200], requireInteraction: false,",
  "      data: { url: '/' },",
  "    }).then(function() {",
  "      scheduleNotification({ delayMs: 604800000, title: n.title, body: n.body, tag: n.tag });",
  "    }).catch(function(err) { console.warn('[SW] Error notificacion:', err); });",
  "  }, n.delayMs);",
  "  classTimers.set(n.tag, id);",
  "}",
  "",
  "self.addEventListener('message', function(event) {",
  "  var d = event.data || {};",
  "  if (d.type === 'SCHEDULE_CLASS_NOTIFICATIONS') {",
  "    cancelAllClassTimers();",
  "    if (Array.isArray(d.notifications)) {",
  "      d.notifications.forEach(function(n) { scheduleNotification(n); });",
  "    }",
  "  }",
  "  if (d.type === 'CANCEL_CLASS_NOTIFICATIONS') { cancelAllClassTimers(); }",
  "});",
  "",
  "self.addEventListener('notificationclick', function(event) {",
  "  event.notification.close();",
  "  var url = (event.notification.data && event.notification.data.url) || '/comunidad';",
  "  event.waitUntil(",
  "    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(list) {",
  "      for (var i = 0; i < list.length; i++) {",
  "        var c = list[i];",
  "        if (c.url.includes(self.location.origin) && 'focus' in c) {",
  "          if ('navigate' in c) c.navigate(url);",
  "          return c.focus();",
  "        }",
  "      }",
  "      if (self.clients.openWindow) return self.clients.openWindow(url);",
  "    })",
  "  );",
  "});",
];

const SW_CONTENT = SW_LINES.join("\n");

export async function GET() {
  return new NextResponse(SW_CONTENT, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
